version: '2'

services:

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  app:
    build: .
    image: node:10
    command: /bin/bash -c "npm install && npm run dev"
    ports:
      - "9001:9001"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb/store
    depends_on:
      - mongodb
    links:
      - mongodb